version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 3

  migrations:
    build: .
    restart: on-failure
    env_file:
      - .env
    command: poetry run alembic upgrade head
    depends_on:
      db:
        condition: service_healthy

  fastapi:
    build: .
    restart: on-failure
    ports:
      - '${API_PORT:-8000}:8000'
    env_file:
      - .env
    volumes:
      - ./${STORAGE_PATH}:/code/${STORAGE_PATH}
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
