"""Audio db creation

Revision ID: 51d7a50512cc
Revises: 8f64c54bfd8f
Create Date: 2023-06-08 16:54:35.489221

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51d7a50512cc'
down_revision = '8f64c54bfd8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('path', sa.String(length=200), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio')
    # ### end Alembic commands ###
